import { expect, test } from "@playwright/test";
import { applicationSchema, workspaceSchema } from "@applymate/contracts";
import { extractText } from "unpdf";
import mammoth from "mammoth";
import { exportDocx, exportPdf } from "../server/src/exports.js";
import { fixturePackage } from "../server/src/fixtures.js";
import { downloadBytes, inspect, login, navigate, sampleJob, sampleResume, uploadText, voiceBaseline } from "./helpers.js";

test.beforeEach(async ({ page, baseURL }) => {
  await page.route("**/*", async (route) => {
    const url = new URL(route.request().url());
    if (["http:", "https:"].includes(url.protocol) && url.origin !== new URL(baseURL!).origin) {
      throw new Error(`Unexpected external browser request: ${url.origin}`);
    }
    await route.continue();
  });
  page.on("pageerror", (error) => { throw error; });
});

test("resume to reviewed documents and an honest application record", async ({ page }, info) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Meet your next chapter." })).toBeVisible();
  await inspect(page, "landing", info);
  await login(page);
  await inspect(page, "overview", info);
  await page.getByRole("button", { name: "Start with your resume", exact: true }).click();
  await uploadText(page);
  await expect(page.locator(".fact-card")).toHaveCount(6);
  await inspect(page, "candidate", info);
  await page.getByRole("button", { name: "Mark proposed facts verified" }).click();
  await page.getByRole("button", { name: "Confirm profile & continue" }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Your voice, not a template");
  await inspect(page, "voice", info);
  await voiceBaseline(page);
  await page.getByLabel("Target roles", { exact: true }).fill("Software Engineer");
  await page.getByLabel("Preferred work arrangement").selectOption("remote");
  await inspect(page, "preferences");
  await page.getByRole("button", { name: "Save preferences" }).click();
  await expect(page.getByRole("button", { name: "Find your next opportunity" })).toBeVisible();
  await navigate(page, "Your voice");
  await page.getByRole("button", { name: "Next prompt" }).click();
  await page.getByRole("button", { name: "Next prompt" }).click();
  await page.getByRole("button", { name: "Save voice profile" }).click();
  await expect(page.getByText("Your writing profile was saved as a new version.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "When things got complicated" })).toBeVisible();
  await expect(page.getByText("Version 2", { exact: false })).toBeVisible();
  await navigate(page, "Answer library");
  await page.getByLabel("Application question").fill("How do you approach a project?");
  await page.getByLabel("Your confirmed answer").fill("I start with a small example and ask for feedback.");
  await page.getByLabel("Reuse permission").selectOption("approved");
  await page.getByRole("button", { name: "Confirm & save answer" }).click();
  await expect(page.getByRole("heading", { name: "How do you approach a project?" })).toBeVisible();
  await inspect(page, "answers");
  await navigate(page, "Opportunities");
  await page.getByLabel("Job title", { exact: true }).fill(sampleJob.title);
  await page.getByLabel("Company", { exact: true }).fill(sampleJob.company);
  await page.getByLabel("Job location", { exact: true }).fill(sampleJob.location);
  await page.getByLabel("Work arrangement", { exact: true }).selectOption(sampleJob.workStyle);
  await page.getByLabel("Job description", { exact: true }).fill(sampleJob.description);
  await page.getByRole("button", { name: "Save & map the evidence" }).click();
  await expect(page.getByRole("heading", { name: "Requirement-to-evidence map" })).toBeVisible();
  await inspect(page, "evidence", info);
  await page.getByRole("button", { name: "Create a draft" }).click();
  await expect(page.getByRole("heading", { name: "Original & proposed wording" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Factual integrity" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve & lock this version" })).toBeDisabled();
  await inspect(page, "review", info);
  await page.getByRole("button", { name: "Approve unchanged statements" }).click();
  await page.getByRole("button", { name: "Save decisions & rerun checks" }).click();
  await expect(page.getByText("Unsaved review changes", { exact: true })).toHaveCount(0);
  await page.getByRole("checkbox", { name: /I checked every included claim/ }).check();
  await page.getByRole("button", { name: "Approve & lock this version" }).click();
  await expect(page.getByRole("heading", { name: "Take your approved story with you." })).toBeVisible();
  await inspect(page, "approved");
  for (const name of ["Resume PDF", "Resume DOCX", "Cover letter PDF", "Cover letter DOCX"]) {
    const { bytes, filename } = await downloadBytes(page, name);
    expect(bytes.length).toBeGreaterThan(1000);
    const text = filename.endsWith(".pdf") ? (await extractText(new Uint8Array(bytes), { mergePages: true })).text :
      (await mammoth.extractRawText({ buffer: bytes })).value;
    expect(text).toContain("Taylor Reed");
    expect(text).toContain("React");
  }
  await page.getByRole("button", { name: "Prepare application record" }).click();
  await expect(page.getByRole("heading", { name: "Your next step is a human one." })).toBeVisible();
  await expect(page.locator(".action-center").getByText("Human Action Required", { exact: true })).toBeVisible();
  await page.getByLabel("Application status").selectOption("Submitted");
  await page.getByLabel("What happened?").fill("Submitted manually through the example employer form.");
  await page.getByLabel("Employer confirmation or reference").fill("Example confirmation EX-100, recorded October 3, 2026.");
  await page.getByRole("button", { name: "Save user-reported update" }).click();
  await expect(page.locator(".action-center").getByText("Submitted", { exact: true })).toBeVisible();
  await page.getByLabel("Application status").selectOption("Interview");
  await page.getByLabel("What happened?").fill("Received an interview invitation from the example employer.");
  await page.getByLabel("Employer confirmation or reference").fill("Example invitation EX-200, recorded October 3, 2026.");
  await page.getByRole("button", { name: "Save user-reported update" }).click();
  await expect(page.locator(".action-center").getByText("Interview", { exact: true })).toBeVisible();
  await expect(page.locator(".timeline")).toContainText("EX-100");
  await expect(page.locator(".timeline")).toContainText("EX-200");
  await inspect(page, "application", info);
  const id = new URL(page.url()).hash.split("/")[1];
  const application = applicationSchema.parse(await (await page.request.get(`/api/applications/${id}`)).json());
  expect(application.answers[0].versions).toHaveLength(1);
  expect(application.snapshot.hash).toHaveLength(64);
  await page.reload();
  await expect(page.locator(".action-center").getByText("Interview", { exact: true })).toBeVisible();
  await navigate(page, "Settings & privacy");
  await inspect(page, "settings", info);
  const exported = await downloadBytes(page, "Export my workspace data");
  const exportedData = JSON.parse(exported.bytes.toString("utf8"));
  expect(exportedData.applications[0].snapshot.hash).toBe(application.snapshot.hash);
  expect(exportedData).not.toHaveProperty("connections");
  expect(exportedData).not.toHaveProperty("sessions");
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0);
});

test("PDF and Word uploads prefill facts and require an explicit merge", async ({ page }) => {
  await login(page);
  await navigate(page, "Candidate profile");
  await page.getByLabel("Resume file").setInputFiles({ name: "synthetic-resume.pdf", mimeType: "application/pdf", buffer: await exportPdf(fixturePackage(), "resume") });
  await page.getByRole("button", { name: "Upload resume", exact: true }).click();
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue("Taylor Reed");
  await expect(page.getByLabel("Resume file")).toHaveValue("");
  await page.getByRole("button", { name: "Mark proposed facts verified" }).click();
  await page.getByRole("button", { name: "Confirm profile & continue" }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Your voice, not a template");
  await navigate(page, "Candidate profile");
  const facts = await page.locator(".fact-card .badge.green").count();
  const docx = await exportDocx(fixturePackage(sampleResume.replace("Taylor Reed", "Taylor Example")), "resume");
  await page.getByLabel("Resume file").setInputFiles({ name: "revised-resume.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: docx });
  await page.getByRole("button", { name: "Upload resume", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Choose what to bring forward" })).toBeVisible();
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue("Taylor Reed");
  const choices = page.locator(".merge-panel").getByRole("checkbox");
  for (const choice of await choices.all()) await expect(choice).not.toBeChecked();
  await inspect(page, "merge");
  await page.locator(".merge-panel").getByRole("checkbox", { name: /Full name/ }).check();
  await page.getByRole("button", { name: "Merge selected proposals" }).click();
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue("Taylor Example");
  await expect(page.locator(".fact-card .badge.green")).toHaveCount(facts);
  await expect(page.getByText("Selected facts merged as proposals. Review them before use.")).toBeVisible();
});

test("accounts stay separate, and deleting an account removes the live session", async ({ page }) => {
  await login(page);
  await navigate(page, "Candidate profile");
  await uploadText(page);
  const first = workspaceSchema.parse(await (await page.request.get("/api/workspace")).json());
  const toggle = page.getByRole("button", { name: "Open navigation" });
  if (await toggle.isVisible()) await toggle.click();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Meet your next chapter." })).toBeVisible();
  await login(page);
  await navigate(page, "Candidate profile");
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue("");
  expect((await page.request.get(`/api/documents/${first.documents[0].id}`)).status()).toBe(404);
  await navigate(page, "Settings & privacy");
  await page.getByLabel("Type DELETE to confirm").fill("DELETE");
  await page.getByRole("button", { name: "Permanently delete local account" }).click();
  await expect(page.getByRole("heading", { name: "Meet your next chapter." })).toBeVisible();
  expect((await page.request.get("/api/workspace")).status()).toBe(401);
});

test("unavailable services and rejected uploads do not become success screens", async ({ page }) => {
  await page.route("**/api/capabilities", (route) => route.abort("failed"));
  await page.goto("/");
  await expect(page.getByRole("alert")).toContainText("Cannot reach ApplyMate");
  await page.unroute("**/api/capabilities");
  await page.getByRole("button", { name: "Try again" }).click();
  await expect(page.getByRole("heading", { name: "Meet your next chapter." })).toBeVisible();
  await login(page);
  await navigate(page, "Candidate profile");
  await page.getByLabel("Resume file").setInputFiles({ name: "not-a-pdf.pdf", mimeType: "application/pdf", buffer: Buffer.from(sampleResume) });
  await page.getByRole("button", { name: "Upload resume", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("not a valid PDF");
  await expect(page.getByLabel("Full name", { exact: true })).toHaveValue("");
  await page.route("**/api/documents", (route) => route.abort("failed"));
  await page.getByLabel("Resume file").setInputFiles({ name: "synthetic.txt", mimeType: "text/plain", buffer: Buffer.from(sampleResume) });
  await page.getByRole("button", { name: "Upload resume", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("Cannot reach ApplyMate");
  await page.unroute("**/api/documents");
  await uploadText(page);
  await expect(page.locator(".document-row")).toHaveCount(1);
});

test("sign-in works by keyboard and navigation remains operable", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("button", { name: "Send sign-in code" })).toBeVisible();
  for (const role of ["menubar", "menu", "grid", "tree", "tablist", "listbox"] as const) expect(await page.getByRole(role).count()).toBe(0);
  await page.keyboard.press("Tab");
  await expect(page.getByRole("link", { name: "ApplyMate home" })).toBeFocused();
  await page.keyboard.press("Enter");
  await page.keyboard.press("Tab");
  await expect(page.getByLabel("Email address", { exact: true })).toBeFocused();
  await page.keyboard.type(`keyboard-${Date.now()}@example.test`);
  await page.keyboard.press("Tab");
  await page.keyboard.press("Space");
  await expect(page.getByRole("checkbox")).toBeChecked();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Enter");
  await expect(page.getByLabel("Verification code", { exact: true })).toBeFocused();
  await page.keyboard.type("12");
  await page.keyboard.press("Backspace");
  await expect(page.getByLabel("Verification code", { exact: true })).toHaveValue("1");
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Open local email preview" })).toBeFocused();
  await page.keyboard.press("Space");
  await expect(page.getByLabel("Verification code", { exact: true })).toHaveValue(/^\d{6}$/);
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Verify and continue" })).toBeFocused();
  await page.keyboard.press("Space");
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Good things start here.");
  await expect(page.getByRole("heading", { level: 1 })).toBeFocused();
  const menu = page.getByRole("button", { name: "Open navigation" });
  if (await menu.isVisible()) {
    await page.keyboard.press("Shift+Tab");
    await expect(menu).toBeFocused();
    await page.keyboard.press("Enter");
    await expect(page.getByRole("button", { name: "Close navigation" })).toHaveAttribute("aria-expanded", "true");
    await inspect(page, "mobile-navigation");
    await page.keyboard.press("Space");
    await expect(menu).toHaveAttribute("aria-expanded", "false");
  }
});
